name=NocML
version=1.0.0
author=Muhammad Ikhwan Fathulloh
maintainer=Muhammad Ikhwan Fathulloh
sentence=A lightweight machine learning library for Arduino.
paragraph=Supports classification (KNN, Naive Bayes), clustering (K-Means), and forecasting (Linear Regression).
category=Data Processing
url=https://github.com/Nocturnailed-Community/NocML
architectures=*
includes=NocML.h
